# This is my docker compose file.
version: '3.4'

# Services
services:

    # Plex
    plex:
        container_name: plex
        environment:
            ADVERTISE_IP: http://192.168.1.111:32400/
            PLEX_GID: 1000
            PLEX_UID: 1000
            TZ: Europe/Amsterdam
            PLEX_CLAIM: claim-oJB1JLGUFJsBDqYfJ1HA
        image: plexinc/pms-docker
        ports:
            - protocol: tcp
              published: 32400
              target: 32400
        restart: unless-stopped
        volumes:
            - /home/alex/.docker/config/plex:/config:rw
            - /tmp/plex:/transcode:rw
            - /mnt/vd0/data/videos:/data:rw
    
    # Portainer
    portainer:
        command: -H unix:///var/run/docker.sock
        container_name: portainer
        environment:
            TZ: Europe/Amsterdam
        image: portainer/portainer
        ports:
            - published: 9000
              target: 9000
        restart: unless-stopped
        volumes:
            - /home/alex/.docker/config/portainer:/data:rw
            - /etc/localtime:/etc/localtime:ro
            - /home/alex/.docker/shared:/shared:rw
            - /var/run/docker.sock:/var/run/docker.sock:rw

