# This is my docker compose file.
version: '3.4'

# Plex
services:
    plex:
        container_name: plex
        environment:
            ADVERTISE_IP: http://192.168.1.111:32400/
            PLEX_GID: 1000
            PLEX_UID: 1000
            TZ: Europe/Amsterdam
            PLEX_CLAIM: claim-oJB1JLGUFJsBDqYfJ1HA
        image: plexinc/pms-docker
        ports:
            - protocol: udp
              published: 32400
              target: 32400
        restart: unless-stopped
        volumes:
            - /home/alex/shn/conf/6-docker/plex:/config:rw
            - /tmp/plex:/transcode:rw
            - /mnt/vd0/data/videos:/data:rw

